# Generated by Django 2.0.3 on 2018-03-26 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escolhas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textp_escolha', models.CharField(max_length=200)),
                ('qtd_votos', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questao_pergunta', models.CharField(max_length=200)),
                ('questao_data_pub', models.DateTimeField(verbose_name='Data de publicacao')),
            ],
        ),
        migrations.AddField(
            model_name='escolhas',
            name='questao_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enquete.Questao'),
        ),
    ]
