# Generated by Django 2.0.3 on 2018-03-26 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquete', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='escolhas',
            old_name='textp_escolha',
            new_name='texto_escolha',
        ),
    ]
